### ISSUE TITLE
fix payment information on website

### ISSUE THREAD

**Issue by Anjola** [isibord/cainafrica-website#10]
fix paypal info and add means of direct donation in place of paystack

**Comment by isibord** [comment]
Thanks for opening this issue. Is there an update to the paypal? Looks like the paypal account is inactive, please notify Ruke to activate.
For the direct donation option, are you recommending to put the Nigerian account details in place of paystack?

**Comment by Anjola** [comment]
Added #11 to fix :)  There is a new paypal addr linked and i've put the Nigerian account details in place of paystack as that is currently broken
